project:
  type: website
  # See https://github.com/quarto-dev/quarto-cli/discussions/382.
  output-dir: docs

format:
  html:
    toc: true
    theme: 
      light: [flatly, tiledb.scss]
    mainfont: Helvetica
    fontsize: 1rem
    linkcolor: "#4d9fff"
    code-copy: true
    code-overflow: wrap
    css: tiledb.css

website:
  favicon: "images/favicon.ico"
  repo-url: https://github.com/johnkerl/quarto-ci-render-experiment
  page-navigation: true
  navbar:
    background: light
    collapse-below: lg
    left:
      - text: "Repo"
        href: "https://github.com/johnkerl/quarto-ci-render-experiment"

  sidebar:
    - id: is-this-used
      title: "Is this used?"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: "index.md"
